In [5]:
import torch

x = [1,2,3,4,5]   # fill in: numbers 1 to 5
y = [2,4,6,8,10]   # fill in: their doubles

x_tensor = torch.tensor(x, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.float32)

print(x_tensor)
print(y_tensor)

tensor([1., 2., 3., 4., 5.])
tensor([ 2.,  4.,  6.,  8., 10.])


In [6]:
x_tensor.shape

torch.Size([5])

In [7]:
x_tensor = x_tensor.reshape(5, -1)
y_tensor = y_tensor.reshape(5, -1)

In [8]:
import torch.nn as nn

In [9]:
class RegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(1, 1)

    def forward(self, x):
        return self.layer(x)

In [10]:
model = RegressionModel()

In [11]:
print(model)

RegressionModel(
  (layer): Linear(in_features=1, out_features=1, bias=True)
)


In [12]:
for name, param in model.named_parameters():
    print(name, param.data)

layer.weight tensor([[-0.1964]])
layer.bias tensor([0.0813])


In [13]:
with torch.no_grad():
    predictions = model(x_tensor)
    print(predictions)

tensor([[-0.1150],
        [-0.3114],
        [-0.5078],
        [-0.7042],
        [-0.9006]])


In [14]:
-0.9930*1 -0.3444

-1.3374

In [15]:
criterion = nn.MSELoss()
loss = criterion(predictions, y_tensor)

In [16]:
print(loss)

tensor(51.9999)


In [17]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [18]:
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [19]:
epochs = 1000

for i in range(epochs):
    # make predictions
    predictions = model(x_tensor)
    # compute loss
    loss = criterion(predictions, y_tensor)
    # zero gradients
    optimizer.zero_grad()
    # backward pass
    loss.backward()
    # update weights
    optimizer.step()
    if i%100 == 0:
        print("Epoch: {} | Loss: {}".format(i, loss.item()))

Epoch: 0 | Loss: 51.99992752075195
Epoch: 100 | Loss: 0.037937555462121964
Epoch: 200 | Loss: 0.019271064549684525
Epoch: 300 | Loss: 0.009789057075977325
Epoch: 400 | Loss: 0.004972526803612709
Epoch: 500 | Loss: 0.002525877673178911
Epoch: 600 | Loss: 0.0012830591294914484
Epoch: 700 | Loss: 0.0006517503061331809
Epoch: 800 | Loss: 0.00033106960472650826
Epoch: 900 | Loss: 0.0001681702706264332


In [20]:
for name, params in model.named_parameters():
    print(name, params)

layer.weight Parameter containing:
tensor([[1.9940]], requires_grad=True)
layer.bias Parameter containing:
tensor([0.0217], requires_grad=True)


In [21]:
with torch.no_grad():
    predictions = model(x_tensor)

In [22]:
criterion(predictions, y_tensor)

tensor(8.5428e-05)

In [23]:
predictions

tensor([[2.0157],
        [4.0097],
        [6.0037],
        [7.9977],
        [9.9917]])